module.exports = {
  docs: [
    {
      type: "category",
      label: "Introduction",
      items: ["presentation"],
    },
    {
      type: "category",
      label: "Contributions",
      items: [
        "contributions/apple-swift-nio1692",
        "contributions/xlayers395",
        "contributions/backstage3794",
        "contributions/lifetime28",
        "contributions/backstage4416",
        "contributions/octobox2597",
        "contributions/consoleme9008",
        "contributions/changesets80",
        "contributions/caramel91",
        "contributions/firefox-ios8327",
        "contributions/driftctl458",
        "contributions/backstage5675",
        "contributions/flutter",
      ],
    },
    {
      type: "category",
      label: "Projects",
      items: [
        "projects/backstage",
        "projects/apple-swift-nio",
        "projects/consoleme",
        "projects/changesets",
        "projects/firefox-ios",
        "projects/xlayers",
        "projects/lifetime",
        "projects/octobox",
        "projects/caramel",
        "projects/driftctl",
        "projects/flutter",
      ],
    },
  ],
};
